const { execSync } = require('child_process');

// Get environment variables
const testExitCode = process.env.TEST_EXIT_CODE;
const coverage = process.env.coverage || 'N/A';
const totalSize = process.env.total_size || 'N/A';
const gzippedSize = process.env.gzipped_size || 'N/A';
const bundleOutput = process.env.bundle_output || 'Bundle size analysis not available';

const testStatus = testExitCode === '0' ? '✅ PASSED' : '❌ FAILED';

const commentBody = `## 🚀 PR Check Results

### ✅ **Tests Status**
- **Status**: ${testStatus}
- **Coverage**: ${coverage}

### 📦 **Bundle Size**
- **Total Size**: ${totalSize}
- **Gzipped Size**: ${gzippedSize}

### 📋 **Build Status**
- **Status**: ✅ SUCCESS
- **Linting**: ✅ PASSED
- **TypeScript Compilation**: ✅ SUCCESS

### 📊 **Detailed Bundle Analysis**
\`\`\`
${bundleOutput}
\`\`\`

---
*This comment was automatically generated by GitHub Actions*`;

console.log(commentBody);